// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.ennew.j2etcdV3.proto.authpb;

public final class Auth {
  private Auth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:authpb.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes name = 1;</code>
     */
    com.google.protobuf.ByteString getName();

    /**
     * <code>optional bytes password = 2;</code>
     */
    com.google.protobuf.ByteString getPassword();

    /**
     * <code>repeated string roles = 3;</code>
     */
    java.util.List<java.lang.String>
        getRolesList();
    /**
     * <code>repeated string roles = 3;</code>
     */
    int getRolesCount();
    /**
     * <code>repeated string roles = 3;</code>
     */
    java.lang.String getRoles(int index);
    /**
     * <code>repeated string roles = 3;</code>
     */
    com.google.protobuf.ByteString
        getRolesBytes(int index);
  }
  /**
   * <pre>
   * User is a single entry in the bucket authUsers
   * </pre>
   *
   * Protobuf type {@code authpb.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:authpb.User)
      UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = com.google.protobuf.ByteString.EMPTY;
      password_ = com.google.protobuf.ByteString.EMPTY;
      roles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              name_ = input.readBytes();
              break;
            }
            case 18: {

              password_ = input.readBytes();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                roles_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              roles_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          roles_ = roles_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ennew.j2etcdV3.proto.authpb.Auth.internal_static_authpb_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ennew.j2etcdV3.proto.authpb.Auth.internal_static_authpb_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ennew.j2etcdV3.proto.authpb.Auth.User.class, com.ennew.j2etcdV3.proto.authpb.Auth.User.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString name_;
    /**
     * <code>optional bytes name = 1;</code>
     */
    public com.google.protobuf.ByteString getName() {
      return name_;
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString password_;
    /**
     * <code>optional bytes password = 2;</code>
     */
    public com.google.protobuf.ByteString getPassword() {
      return password_;
    }

    public static final int ROLES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList roles_;
    /**
     * <code>repeated string roles = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getRolesList() {
      return roles_;
    }
    /**
     * <code>repeated string roles = 3;</code>
     */
    public int getRolesCount() {
      return roles_.size();
    }
    /**
     * <code>repeated string roles = 3;</code>
     */
    public java.lang.String getRoles(int index) {
      return roles_.get(index);
    }
    /**
     * <code>repeated string roles = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRolesBytes(int index) {
      return roles_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!name_.isEmpty()) {
        output.writeBytes(1, name_);
      }
      if (!password_.isEmpty()) {
        output.writeBytes(2, password_);
      }
      for (int i = 0; i < roles_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, roles_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!name_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, name_);
      }
      if (!password_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, password_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < roles_.size(); i++) {
          dataSize += computeStringSizeNoTag(roles_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRolesList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ennew.j2etcdV3.proto.authpb.Auth.User)) {
        return super.equals(obj);
      }
      com.ennew.j2etcdV3.proto.authpb.Auth.User other = (com.ennew.j2etcdV3.proto.authpb.Auth.User) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && getRolesList()
          .equals(other.getRolesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      if (getRolesCount() > 0) {
        hash = (37 * hash) + ROLES_FIELD_NUMBER;
        hash = (53 * hash) + getRolesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ennew.j2etcdV3.proto.authpb.Auth.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ennew.j2etcdV3.proto.authpb.Auth.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * User is a single entry in the bucket authUsers
     * </pre>
     *
     * Protobuf type {@code authpb.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:authpb.User)
        com.ennew.j2etcdV3.proto.authpb.Auth.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ennew.j2etcdV3.proto.authpb.Auth.internal_static_authpb_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ennew.j2etcdV3.proto.authpb.Auth.internal_static_authpb_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ennew.j2etcdV3.proto.authpb.Auth.User.class, com.ennew.j2etcdV3.proto.authpb.Auth.User.Builder.class);
      }

      // Construct using com.ennew.j2etcdV3.proto.authpb.Auth.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = com.google.protobuf.ByteString.EMPTY;

        password_ = com.google.protobuf.ByteString.EMPTY;

        roles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ennew.j2etcdV3.proto.authpb.Auth.internal_static_authpb_User_descriptor;
      }

      public com.ennew.j2etcdV3.proto.authpb.Auth.User getDefaultInstanceForType() {
        return com.ennew.j2etcdV3.proto.authpb.Auth.User.getDefaultInstance();
      }

      public com.ennew.j2etcdV3.proto.authpb.Auth.User build() {
        com.ennew.j2etcdV3.proto.authpb.Auth.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ennew.j2etcdV3.proto.authpb.Auth.User buildPartial() {
        com.ennew.j2etcdV3.proto.authpb.Auth.User result = new com.ennew.j2etcdV3.proto.authpb.Auth.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        result.password_ = password_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          roles_ = roles_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.roles_ = roles_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ennew.j2etcdV3.proto.authpb.Auth.User) {
          return mergeFrom((com.ennew.j2etcdV3.proto.authpb.Auth.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ennew.j2etcdV3.proto.authpb.Auth.User other) {
        if (other == com.ennew.j2etcdV3.proto.authpb.Auth.User.getDefaultInstance()) return this;
        if (other.getName() != com.google.protobuf.ByteString.EMPTY) {
          setName(other.getName());
        }
        if (other.getPassword() != com.google.protobuf.ByteString.EMPTY) {
          setPassword(other.getPassword());
        }
        if (!other.roles_.isEmpty()) {
          if (roles_.isEmpty()) {
            roles_ = other.roles_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureRolesIsMutable();
            roles_.addAll(other.roles_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ennew.j2etcdV3.proto.authpb.Auth.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ennew.j2etcdV3.proto.authpb.Auth.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString name_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes name = 1;</code>
       */
      public com.google.protobuf.ByteString getName() {
        return name_;
      }
      /**
       * <code>optional bytes name = 1;</code>
       */
      public Builder setName(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString password_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes password = 2;</code>
       */
      public com.google.protobuf.ByteString getPassword() {
        return password_;
      }
      /**
       * <code>optional bytes password = 2;</code>
       */
      public Builder setPassword(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes password = 2;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList roles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRolesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          roles_ = new com.google.protobuf.LazyStringArrayList(roles_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string roles = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getRolesList() {
        return roles_.getUnmodifiableView();
      }
      /**
       * <code>repeated string roles = 3;</code>
       */
      public int getRolesCount() {
        return roles_.size();
      }
      /**
       * <code>repeated string roles = 3;</code>
       */
      public java.lang.String getRoles(int index) {
        return roles_.get(index);
      }
      /**
       * <code>repeated string roles = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRolesBytes(int index) {
        return roles_.getByteString(index);
      }
      /**
       * <code>repeated string roles = 3;</code>
       */
      public Builder setRoles(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRolesIsMutable();
        roles_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string roles = 3;</code>
       */
      public Builder addRoles(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRolesIsMutable();
        roles_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string roles = 3;</code>
       */
      public Builder addAllRoles(
          java.lang.Iterable<java.lang.String> values) {
        ensureRolesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, roles_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string roles = 3;</code>
       */
      public Builder clearRoles() {
        roles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string roles = 3;</code>
       */
      public Builder addRolesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureRolesIsMutable();
        roles_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:authpb.User)
    }

    // @@protoc_insertion_point(class_scope:authpb.User)
    private static final com.ennew.j2etcdV3.proto.authpb.Auth.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ennew.j2etcdV3.proto.authpb.Auth.User();
    }

    public static com.ennew.j2etcdV3.proto.authpb.Auth.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public com.ennew.j2etcdV3.proto.authpb.Auth.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PermissionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:authpb.Permission)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .authpb.Permission.Type permType = 1;</code>
     */
    int getPermTypeValue();
    /**
     * <code>optional .authpb.Permission.Type permType = 1;</code>
     */
    com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Type getPermType();

    /**
     * <code>optional bytes key = 2;</code>
     */
    com.google.protobuf.ByteString getKey();

    /**
     * <code>optional bytes range_end = 3;</code>
     */
    com.google.protobuf.ByteString getRangeEnd();
  }
  /**
   * <pre>
   * Permission is a single entity
   * </pre>
   *
   * Protobuf type {@code authpb.Permission}
   */
  public  static final class Permission extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:authpb.Permission)
      PermissionOrBuilder {
    // Use Permission.newBuilder() to construct.
    private Permission(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Permission() {
      permType_ = 0;
      key_ = com.google.protobuf.ByteString.EMPTY;
      rangeEnd_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Permission(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              permType_ = rawValue;
              break;
            }
            case 18: {

              key_ = input.readBytes();
              break;
            }
            case 26: {

              rangeEnd_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ennew.j2etcdV3.proto.authpb.Auth.internal_static_authpb_Permission_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ennew.j2etcdV3.proto.authpb.Auth.internal_static_authpb_Permission_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ennew.j2etcdV3.proto.authpb.Auth.Permission.class, com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Builder.class);
    }

    /**
     * Protobuf enum {@code authpb.Permission.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>READ = 0;</code>
       */
      READ(0),
      /**
       * <code>WRITE = 1;</code>
       */
      WRITE(1),
      /**
       * <code>READWRITE = 2;</code>
       */
      READWRITE(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>READ = 0;</code>
       */
      public static final int READ_VALUE = 0;
      /**
       * <code>WRITE = 1;</code>
       */
      public static final int WRITE_VALUE = 1;
      /**
       * <code>READWRITE = 2;</code>
       */
      public static final int READWRITE_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return READ;
          case 1: return WRITE;
          case 2: return READWRITE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.ennew.j2etcdV3.proto.authpb.Auth.Permission.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:authpb.Permission.Type)
    }

    public static final int PERMTYPE_FIELD_NUMBER = 1;
    private int permType_;
    /**
     * <code>optional .authpb.Permission.Type permType = 1;</code>
     */
    public int getPermTypeValue() {
      return permType_;
    }
    /**
     * <code>optional .authpb.Permission.Type permType = 1;</code>
     */
    public com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Type getPermType() {
      com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Type result = com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Type.valueOf(permType_);
      return result == null ? com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Type.UNRECOGNIZED : result;
    }

    public static final int KEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString key_;
    /**
     * <code>optional bytes key = 2;</code>
     */
    public com.google.protobuf.ByteString getKey() {
      return key_;
    }

    public static final int RANGE_END_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString rangeEnd_;
    /**
     * <code>optional bytes range_end = 3;</code>
     */
    public com.google.protobuf.ByteString getRangeEnd() {
      return rangeEnd_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (permType_ != com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Type.READ.getNumber()) {
        output.writeEnum(1, permType_);
      }
      if (!key_.isEmpty()) {
        output.writeBytes(2, key_);
      }
      if (!rangeEnd_.isEmpty()) {
        output.writeBytes(3, rangeEnd_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (permType_ != com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Type.READ.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, permType_);
      }
      if (!key_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, key_);
      }
      if (!rangeEnd_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, rangeEnd_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ennew.j2etcdV3.proto.authpb.Auth.Permission)) {
        return super.equals(obj);
      }
      com.ennew.j2etcdV3.proto.authpb.Auth.Permission other = (com.ennew.j2etcdV3.proto.authpb.Auth.Permission) obj;

      boolean result = true;
      result = result && permType_ == other.permType_;
      result = result && getKey()
          .equals(other.getKey());
      result = result && getRangeEnd()
          .equals(other.getRangeEnd());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PERMTYPE_FIELD_NUMBER;
      hash = (53 * hash) + permType_;
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + RANGE_END_FIELD_NUMBER;
      hash = (53 * hash) + getRangeEnd().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ennew.j2etcdV3.proto.authpb.Auth.Permission parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.Permission parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.Permission parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.Permission parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.Permission parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.Permission parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.Permission parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.Permission parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.Permission parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.Permission parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ennew.j2etcdV3.proto.authpb.Auth.Permission prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Permission is a single entity
     * </pre>
     *
     * Protobuf type {@code authpb.Permission}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:authpb.Permission)
        com.ennew.j2etcdV3.proto.authpb.Auth.PermissionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ennew.j2etcdV3.proto.authpb.Auth.internal_static_authpb_Permission_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ennew.j2etcdV3.proto.authpb.Auth.internal_static_authpb_Permission_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ennew.j2etcdV3.proto.authpb.Auth.Permission.class, com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Builder.class);
      }

      // Construct using com.ennew.j2etcdV3.proto.authpb.Auth.Permission.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        permType_ = 0;

        key_ = com.google.protobuf.ByteString.EMPTY;

        rangeEnd_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ennew.j2etcdV3.proto.authpb.Auth.internal_static_authpb_Permission_descriptor;
      }

      public com.ennew.j2etcdV3.proto.authpb.Auth.Permission getDefaultInstanceForType() {
        return com.ennew.j2etcdV3.proto.authpb.Auth.Permission.getDefaultInstance();
      }

      public com.ennew.j2etcdV3.proto.authpb.Auth.Permission build() {
        com.ennew.j2etcdV3.proto.authpb.Auth.Permission result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ennew.j2etcdV3.proto.authpb.Auth.Permission buildPartial() {
        com.ennew.j2etcdV3.proto.authpb.Auth.Permission result = new com.ennew.j2etcdV3.proto.authpb.Auth.Permission(this);
        result.permType_ = permType_;
        result.key_ = key_;
        result.rangeEnd_ = rangeEnd_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ennew.j2etcdV3.proto.authpb.Auth.Permission) {
          return mergeFrom((com.ennew.j2etcdV3.proto.authpb.Auth.Permission)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ennew.j2etcdV3.proto.authpb.Auth.Permission other) {
        if (other == com.ennew.j2etcdV3.proto.authpb.Auth.Permission.getDefaultInstance()) return this;
        if (other.permType_ != 0) {
          setPermTypeValue(other.getPermTypeValue());
        }
        if (other.getKey() != com.google.protobuf.ByteString.EMPTY) {
          setKey(other.getKey());
        }
        if (other.getRangeEnd() != com.google.protobuf.ByteString.EMPTY) {
          setRangeEnd(other.getRangeEnd());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ennew.j2etcdV3.proto.authpb.Auth.Permission parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ennew.j2etcdV3.proto.authpb.Auth.Permission) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int permType_ = 0;
      /**
       * <code>optional .authpb.Permission.Type permType = 1;</code>
       */
      public int getPermTypeValue() {
        return permType_;
      }
      /**
       * <code>optional .authpb.Permission.Type permType = 1;</code>
       */
      public Builder setPermTypeValue(int value) {
        permType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .authpb.Permission.Type permType = 1;</code>
       */
      public com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Type getPermType() {
        com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Type result = com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Type.valueOf(permType_);
        return result == null ? com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .authpb.Permission.Type permType = 1;</code>
       */
      public Builder setPermType(com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        permType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .authpb.Permission.Type permType = 1;</code>
       */
      public Builder clearPermType() {
        
        permType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes key = 2;</code>
       */
      public com.google.protobuf.ByteString getKey() {
        return key_;
      }
      /**
       * <code>optional bytes key = 2;</code>
       */
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes key = 2;</code>
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString rangeEnd_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes range_end = 3;</code>
       */
      public com.google.protobuf.ByteString getRangeEnd() {
        return rangeEnd_;
      }
      /**
       * <code>optional bytes range_end = 3;</code>
       */
      public Builder setRangeEnd(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rangeEnd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes range_end = 3;</code>
       */
      public Builder clearRangeEnd() {
        
        rangeEnd_ = getDefaultInstance().getRangeEnd();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:authpb.Permission)
    }

    // @@protoc_insertion_point(class_scope:authpb.Permission)
    private static final com.ennew.j2etcdV3.proto.authpb.Auth.Permission DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ennew.j2etcdV3.proto.authpb.Auth.Permission();
    }

    public static com.ennew.j2etcdV3.proto.authpb.Auth.Permission getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Permission>
        PARSER = new com.google.protobuf.AbstractParser<Permission>() {
      public Permission parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Permission(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Permission> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Permission> getParserForType() {
      return PARSER;
    }

    public com.ennew.j2etcdV3.proto.authpb.Auth.Permission getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RoleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:authpb.Role)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes name = 1;</code>
     */
    com.google.protobuf.ByteString getName();

    /**
     * <code>repeated .authpb.Permission keyPermission = 2;</code>
     */
    java.util.List<com.ennew.j2etcdV3.proto.authpb.Auth.Permission> 
        getKeyPermissionList();
    /**
     * <code>repeated .authpb.Permission keyPermission = 2;</code>
     */
    com.ennew.j2etcdV3.proto.authpb.Auth.Permission getKeyPermission(int index);
    /**
     * <code>repeated .authpb.Permission keyPermission = 2;</code>
     */
    int getKeyPermissionCount();
    /**
     * <code>repeated .authpb.Permission keyPermission = 2;</code>
     */
    java.util.List<? extends com.ennew.j2etcdV3.proto.authpb.Auth.PermissionOrBuilder> 
        getKeyPermissionOrBuilderList();
    /**
     * <code>repeated .authpb.Permission keyPermission = 2;</code>
     */
    com.ennew.j2etcdV3.proto.authpb.Auth.PermissionOrBuilder getKeyPermissionOrBuilder(
        int index);
  }
  /**
   * <pre>
   * Role is a single entry in the bucket authRoles
   * </pre>
   *
   * Protobuf type {@code authpb.Role}
   */
  public  static final class Role extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:authpb.Role)
      RoleOrBuilder {
    // Use Role.newBuilder() to construct.
    private Role(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Role() {
      name_ = com.google.protobuf.ByteString.EMPTY;
      keyPermission_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Role(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              name_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                keyPermission_ = new java.util.ArrayList<com.ennew.j2etcdV3.proto.authpb.Auth.Permission>();
                mutable_bitField0_ |= 0x00000002;
              }
              keyPermission_.add(
                  input.readMessage(com.ennew.j2etcdV3.proto.authpb.Auth.Permission.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          keyPermission_ = java.util.Collections.unmodifiableList(keyPermission_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ennew.j2etcdV3.proto.authpb.Auth.internal_static_authpb_Role_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ennew.j2etcdV3.proto.authpb.Auth.internal_static_authpb_Role_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ennew.j2etcdV3.proto.authpb.Auth.Role.class, com.ennew.j2etcdV3.proto.authpb.Auth.Role.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString name_;
    /**
     * <code>optional bytes name = 1;</code>
     */
    public com.google.protobuf.ByteString getName() {
      return name_;
    }

    public static final int KEYPERMISSION_FIELD_NUMBER = 2;
    private java.util.List<com.ennew.j2etcdV3.proto.authpb.Auth.Permission> keyPermission_;
    /**
     * <code>repeated .authpb.Permission keyPermission = 2;</code>
     */
    public java.util.List<com.ennew.j2etcdV3.proto.authpb.Auth.Permission> getKeyPermissionList() {
      return keyPermission_;
    }
    /**
     * <code>repeated .authpb.Permission keyPermission = 2;</code>
     */
    public java.util.List<? extends com.ennew.j2etcdV3.proto.authpb.Auth.PermissionOrBuilder> 
        getKeyPermissionOrBuilderList() {
      return keyPermission_;
    }
    /**
     * <code>repeated .authpb.Permission keyPermission = 2;</code>
     */
    public int getKeyPermissionCount() {
      return keyPermission_.size();
    }
    /**
     * <code>repeated .authpb.Permission keyPermission = 2;</code>
     */
    public com.ennew.j2etcdV3.proto.authpb.Auth.Permission getKeyPermission(int index) {
      return keyPermission_.get(index);
    }
    /**
     * <code>repeated .authpb.Permission keyPermission = 2;</code>
     */
    public com.ennew.j2etcdV3.proto.authpb.Auth.PermissionOrBuilder getKeyPermissionOrBuilder(
        int index) {
      return keyPermission_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!name_.isEmpty()) {
        output.writeBytes(1, name_);
      }
      for (int i = 0; i < keyPermission_.size(); i++) {
        output.writeMessage(2, keyPermission_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!name_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, name_);
      }
      for (int i = 0; i < keyPermission_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, keyPermission_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ennew.j2etcdV3.proto.authpb.Auth.Role)) {
        return super.equals(obj);
      }
      com.ennew.j2etcdV3.proto.authpb.Auth.Role other = (com.ennew.j2etcdV3.proto.authpb.Auth.Role) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && getKeyPermissionList()
          .equals(other.getKeyPermissionList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getKeyPermissionCount() > 0) {
        hash = (37 * hash) + KEYPERMISSION_FIELD_NUMBER;
        hash = (53 * hash) + getKeyPermissionList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ennew.j2etcdV3.proto.authpb.Auth.Role parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.Role parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.Role parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.Role parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.Role parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.Role parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.Role parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.Role parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.Role parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ennew.j2etcdV3.proto.authpb.Auth.Role parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ennew.j2etcdV3.proto.authpb.Auth.Role prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Role is a single entry in the bucket authRoles
     * </pre>
     *
     * Protobuf type {@code authpb.Role}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:authpb.Role)
        com.ennew.j2etcdV3.proto.authpb.Auth.RoleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ennew.j2etcdV3.proto.authpb.Auth.internal_static_authpb_Role_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ennew.j2etcdV3.proto.authpb.Auth.internal_static_authpb_Role_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ennew.j2etcdV3.proto.authpb.Auth.Role.class, com.ennew.j2etcdV3.proto.authpb.Auth.Role.Builder.class);
      }

      // Construct using com.ennew.j2etcdV3.proto.authpb.Auth.Role.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getKeyPermissionFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = com.google.protobuf.ByteString.EMPTY;

        if (keyPermissionBuilder_ == null) {
          keyPermission_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          keyPermissionBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ennew.j2etcdV3.proto.authpb.Auth.internal_static_authpb_Role_descriptor;
      }

      public com.ennew.j2etcdV3.proto.authpb.Auth.Role getDefaultInstanceForType() {
        return com.ennew.j2etcdV3.proto.authpb.Auth.Role.getDefaultInstance();
      }

      public com.ennew.j2etcdV3.proto.authpb.Auth.Role build() {
        com.ennew.j2etcdV3.proto.authpb.Auth.Role result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ennew.j2etcdV3.proto.authpb.Auth.Role buildPartial() {
        com.ennew.j2etcdV3.proto.authpb.Auth.Role result = new com.ennew.j2etcdV3.proto.authpb.Auth.Role(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        if (keyPermissionBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            keyPermission_ = java.util.Collections.unmodifiableList(keyPermission_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.keyPermission_ = keyPermission_;
        } else {
          result.keyPermission_ = keyPermissionBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ennew.j2etcdV3.proto.authpb.Auth.Role) {
          return mergeFrom((com.ennew.j2etcdV3.proto.authpb.Auth.Role)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ennew.j2etcdV3.proto.authpb.Auth.Role other) {
        if (other == com.ennew.j2etcdV3.proto.authpb.Auth.Role.getDefaultInstance()) return this;
        if (other.getName() != com.google.protobuf.ByteString.EMPTY) {
          setName(other.getName());
        }
        if (keyPermissionBuilder_ == null) {
          if (!other.keyPermission_.isEmpty()) {
            if (keyPermission_.isEmpty()) {
              keyPermission_ = other.keyPermission_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureKeyPermissionIsMutable();
              keyPermission_.addAll(other.keyPermission_);
            }
            onChanged();
          }
        } else {
          if (!other.keyPermission_.isEmpty()) {
            if (keyPermissionBuilder_.isEmpty()) {
              keyPermissionBuilder_.dispose();
              keyPermissionBuilder_ = null;
              keyPermission_ = other.keyPermission_;
              bitField0_ = (bitField0_ & ~0x00000002);
              keyPermissionBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getKeyPermissionFieldBuilder() : null;
            } else {
              keyPermissionBuilder_.addAllMessages(other.keyPermission_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ennew.j2etcdV3.proto.authpb.Auth.Role parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ennew.j2etcdV3.proto.authpb.Auth.Role) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString name_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes name = 1;</code>
       */
      public com.google.protobuf.ByteString getName() {
        return name_;
      }
      /**
       * <code>optional bytes name = 1;</code>
       */
      public Builder setName(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }

      private java.util.List<com.ennew.j2etcdV3.proto.authpb.Auth.Permission> keyPermission_ =
        java.util.Collections.emptyList();
      private void ensureKeyPermissionIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          keyPermission_ = new java.util.ArrayList<com.ennew.j2etcdV3.proto.authpb.Auth.Permission>(keyPermission_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ennew.j2etcdV3.proto.authpb.Auth.Permission, com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Builder, com.ennew.j2etcdV3.proto.authpb.Auth.PermissionOrBuilder> keyPermissionBuilder_;

      /**
       * <code>repeated .authpb.Permission keyPermission = 2;</code>
       */
      public java.util.List<com.ennew.j2etcdV3.proto.authpb.Auth.Permission> getKeyPermissionList() {
        if (keyPermissionBuilder_ == null) {
          return java.util.Collections.unmodifiableList(keyPermission_);
        } else {
          return keyPermissionBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .authpb.Permission keyPermission = 2;</code>
       */
      public int getKeyPermissionCount() {
        if (keyPermissionBuilder_ == null) {
          return keyPermission_.size();
        } else {
          return keyPermissionBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .authpb.Permission keyPermission = 2;</code>
       */
      public com.ennew.j2etcdV3.proto.authpb.Auth.Permission getKeyPermission(int index) {
        if (keyPermissionBuilder_ == null) {
          return keyPermission_.get(index);
        } else {
          return keyPermissionBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .authpb.Permission keyPermission = 2;</code>
       */
      public Builder setKeyPermission(
          int index, com.ennew.j2etcdV3.proto.authpb.Auth.Permission value) {
        if (keyPermissionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeyPermissionIsMutable();
          keyPermission_.set(index, value);
          onChanged();
        } else {
          keyPermissionBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .authpb.Permission keyPermission = 2;</code>
       */
      public Builder setKeyPermission(
          int index, com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Builder builderForValue) {
        if (keyPermissionBuilder_ == null) {
          ensureKeyPermissionIsMutable();
          keyPermission_.set(index, builderForValue.build());
          onChanged();
        } else {
          keyPermissionBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .authpb.Permission keyPermission = 2;</code>
       */
      public Builder addKeyPermission(com.ennew.j2etcdV3.proto.authpb.Auth.Permission value) {
        if (keyPermissionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeyPermissionIsMutable();
          keyPermission_.add(value);
          onChanged();
        } else {
          keyPermissionBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .authpb.Permission keyPermission = 2;</code>
       */
      public Builder addKeyPermission(
          int index, com.ennew.j2etcdV3.proto.authpb.Auth.Permission value) {
        if (keyPermissionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKeyPermissionIsMutable();
          keyPermission_.add(index, value);
          onChanged();
        } else {
          keyPermissionBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .authpb.Permission keyPermission = 2;</code>
       */
      public Builder addKeyPermission(
          com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Builder builderForValue) {
        if (keyPermissionBuilder_ == null) {
          ensureKeyPermissionIsMutable();
          keyPermission_.add(builderForValue.build());
          onChanged();
        } else {
          keyPermissionBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .authpb.Permission keyPermission = 2;</code>
       */
      public Builder addKeyPermission(
          int index, com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Builder builderForValue) {
        if (keyPermissionBuilder_ == null) {
          ensureKeyPermissionIsMutable();
          keyPermission_.add(index, builderForValue.build());
          onChanged();
        } else {
          keyPermissionBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .authpb.Permission keyPermission = 2;</code>
       */
      public Builder addAllKeyPermission(
          java.lang.Iterable<? extends com.ennew.j2etcdV3.proto.authpb.Auth.Permission> values) {
        if (keyPermissionBuilder_ == null) {
          ensureKeyPermissionIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, keyPermission_);
          onChanged();
        } else {
          keyPermissionBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .authpb.Permission keyPermission = 2;</code>
       */
      public Builder clearKeyPermission() {
        if (keyPermissionBuilder_ == null) {
          keyPermission_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          keyPermissionBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .authpb.Permission keyPermission = 2;</code>
       */
      public Builder removeKeyPermission(int index) {
        if (keyPermissionBuilder_ == null) {
          ensureKeyPermissionIsMutable();
          keyPermission_.remove(index);
          onChanged();
        } else {
          keyPermissionBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .authpb.Permission keyPermission = 2;</code>
       */
      public com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Builder getKeyPermissionBuilder(
          int index) {
        return getKeyPermissionFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .authpb.Permission keyPermission = 2;</code>
       */
      public com.ennew.j2etcdV3.proto.authpb.Auth.PermissionOrBuilder getKeyPermissionOrBuilder(
          int index) {
        if (keyPermissionBuilder_ == null) {
          return keyPermission_.get(index);  } else {
          return keyPermissionBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .authpb.Permission keyPermission = 2;</code>
       */
      public java.util.List<? extends com.ennew.j2etcdV3.proto.authpb.Auth.PermissionOrBuilder> 
           getKeyPermissionOrBuilderList() {
        if (keyPermissionBuilder_ != null) {
          return keyPermissionBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(keyPermission_);
        }
      }
      /**
       * <code>repeated .authpb.Permission keyPermission = 2;</code>
       */
      public com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Builder addKeyPermissionBuilder() {
        return getKeyPermissionFieldBuilder().addBuilder(
            com.ennew.j2etcdV3.proto.authpb.Auth.Permission.getDefaultInstance());
      }
      /**
       * <code>repeated .authpb.Permission keyPermission = 2;</code>
       */
      public com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Builder addKeyPermissionBuilder(
          int index) {
        return getKeyPermissionFieldBuilder().addBuilder(
            index, com.ennew.j2etcdV3.proto.authpb.Auth.Permission.getDefaultInstance());
      }
      /**
       * <code>repeated .authpb.Permission keyPermission = 2;</code>
       */
      public java.util.List<com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Builder> 
           getKeyPermissionBuilderList() {
        return getKeyPermissionFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ennew.j2etcdV3.proto.authpb.Auth.Permission, com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Builder, com.ennew.j2etcdV3.proto.authpb.Auth.PermissionOrBuilder> 
          getKeyPermissionFieldBuilder() {
        if (keyPermissionBuilder_ == null) {
          keyPermissionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.ennew.j2etcdV3.proto.authpb.Auth.Permission, com.ennew.j2etcdV3.proto.authpb.Auth.Permission.Builder, com.ennew.j2etcdV3.proto.authpb.Auth.PermissionOrBuilder>(
                  keyPermission_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          keyPermission_ = null;
        }
        return keyPermissionBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:authpb.Role)
    }

    // @@protoc_insertion_point(class_scope:authpb.Role)
    private static final com.ennew.j2etcdV3.proto.authpb.Auth.Role DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ennew.j2etcdV3.proto.authpb.Auth.Role();
    }

    public static com.ennew.j2etcdV3.proto.authpb.Auth.Role getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Role>
        PARSER = new com.google.protobuf.AbstractParser<Role>() {
      public Role parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Role(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Role> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Role> getParserForType() {
      return PARSER;
    }

    public com.ennew.j2etcdV3.proto.authpb.Auth.Role getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authpb_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_authpb_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authpb_Permission_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_authpb_Permission_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authpb_Role_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_authpb_Role_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nauth.proto\022\006authpb\032\024gogoproto/gogo.pro" +
      "to\"5\n\004User\022\014\n\004name\030\001 \001(\014\022\020\n\010password\030\002 \001" +
      "(\014\022\r\n\005roles\030\003 \003(\t\"\203\001\n\nPermission\022)\n\010perm" +
      "Type\030\001 \001(\0162\027.authpb.Permission.Type\022\013\n\003k" +
      "ey\030\002 \001(\014\022\021\n\trange_end\030\003 \001(\014\"*\n\004Type\022\010\n\004R" +
      "EAD\020\000\022\t\n\005WRITE\020\001\022\r\n\tREADWRITE\020\002\"?\n\004Role\022" +
      "\014\n\004name\030\001 \001(\014\022)\n\rkeyPermission\030\002 \003(\0132\022.a" +
      "uthpb.PermissionB5\n\037com.ennew.j2etcdV3.p" +
      "roto.authpb\310\342\036\001\340\342\036\001\320\342\036\001\310\341\036\000\320\341\036\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        }, assigner);
    internal_static_authpb_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_authpb_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_authpb_User_descriptor,
        new java.lang.String[] { "Name", "Password", "Roles", });
    internal_static_authpb_Permission_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_authpb_Permission_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_authpb_Permission_descriptor,
        new java.lang.String[] { "PermType", "Key", "RangeEnd", });
    internal_static_authpb_Role_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_authpb_Role_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_authpb_Role_descriptor,
        new java.lang.String[] { "Name", "KeyPermission", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.goprotoEnumPrefixAll);
    registry.add(com.google.protobuf.GoGoProtos.goprotoGettersAll);
    registry.add(com.google.protobuf.GoGoProtos.marshalerAll);
    registry.add(com.google.protobuf.GoGoProtos.sizerAll);
    registry.add(com.google.protobuf.GoGoProtos.unmarshalerAll);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
