// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lease.proto

package com.ennew.j2etcdV3.proto.leasepb;

public final class LeaseOuterClass {
  private LeaseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LeaseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:leasepb.Lease)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 ID = 1;</code>
     */
    long getID();

    /**
     * <code>optional int64 TTL = 2;</code>
     */
    long getTTL();
  }
  /**
   * Protobuf type {@code leasepb.Lease}
   */
  public  static final class Lease extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:leasepb.Lease)
      LeaseOrBuilder {
    // Use Lease.newBuilder() to construct.
    private Lease(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Lease() {
      iD_ = 0L;
      tTL_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Lease(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              iD_ = input.readInt64();
              break;
            }
            case 16: {

              tTL_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.internal_static_leasepb_Lease_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.internal_static_leasepb_Lease_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease.class, com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long iD_;
    /**
     * <code>optional int64 ID = 1;</code>
     */
    public long getID() {
      return iD_;
    }

    public static final int TTL_FIELD_NUMBER = 2;
    private long tTL_;
    /**
     * <code>optional int64 TTL = 2;</code>
     */
    public long getTTL() {
      return tTL_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (iD_ != 0L) {
        output.writeInt64(1, iD_);
      }
      if (tTL_ != 0L) {
        output.writeInt64(2, tTL_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (iD_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, iD_);
      }
      if (tTL_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, tTL_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease)) {
        return super.equals(obj);
      }
      com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease other = (com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease) obj;

      boolean result = true;
      result = result && (getID()
          == other.getID());
      result = result && (getTTL()
          == other.getTTL());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getID());
      hash = (37 * hash) + TTL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTTL());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code leasepb.Lease}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:leasepb.Lease)
        com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.LeaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.internal_static_leasepb_Lease_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.internal_static_leasepb_Lease_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease.class, com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease.Builder.class);
      }

      // Construct using com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        iD_ = 0L;

        tTL_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.internal_static_leasepb_Lease_descriptor;
      }

      public com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease getDefaultInstanceForType() {
        return com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease.getDefaultInstance();
      }

      public com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease build() {
        com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease buildPartial() {
        com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease result = new com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease(this);
        result.iD_ = iD_;
        result.tTL_ = tTL_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease) {
          return mergeFrom((com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease other) {
        if (other == com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease.getDefaultInstance()) return this;
        if (other.getID() != 0L) {
          setID(other.getID());
        }
        if (other.getTTL() != 0L) {
          setTTL(other.getTTL());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long iD_ ;
      /**
       * <code>optional int64 ID = 1;</code>
       */
      public long getID() {
        return iD_;
      }
      /**
       * <code>optional int64 ID = 1;</code>
       */
      public Builder setID(long value) {
        
        iD_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 ID = 1;</code>
       */
      public Builder clearID() {
        
        iD_ = 0L;
        onChanged();
        return this;
      }

      private long tTL_ ;
      /**
       * <code>optional int64 TTL = 2;</code>
       */
      public long getTTL() {
        return tTL_;
      }
      /**
       * <code>optional int64 TTL = 2;</code>
       */
      public Builder setTTL(long value) {
        
        tTL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 TTL = 2;</code>
       */
      public Builder clearTTL() {
        
        tTL_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:leasepb.Lease)
    }

    // @@protoc_insertion_point(class_scope:leasepb.Lease)
    private static final com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease();
    }

    public static com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Lease>
        PARSER = new com.google.protobuf.AbstractParser<Lease>() {
      public Lease parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Lease(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Lease> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Lease> getParserForType() {
      return PARSER;
    }

    public com.ennew.j2etcdV3.proto.leasepb.LeaseOuterClass.Lease getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_leasepb_Lease_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_leasepb_Lease_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013lease.proto\022\007leasepb\032\024gogoproto/gogo.p" +
      "roto\" \n\005Lease\022\n\n\002ID\030\001 \001(\003\022\013\n\003TTL\030\002 \001(\003B6" +
      "\n com.ennew.j2etcdV3.proto.leasepb\310\342\036\001\340\342" +
      "\036\001\320\342\036\001\310\341\036\000\320\341\036\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        }, assigner);
    internal_static_leasepb_Lease_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_leasepb_Lease_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_leasepb_Lease_descriptor,
        new java.lang.String[] { "ID", "TTL", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.goprotoEnumPrefixAll);
    registry.add(com.google.protobuf.GoGoProtos.goprotoGettersAll);
    registry.add(com.google.protobuf.GoGoProtos.marshalerAll);
    registry.add(com.google.protobuf.GoGoProtos.sizerAll);
    registry.add(com.google.protobuf.GoGoProtos.unmarshalerAll);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
