// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: etcdserver.proto

package com.ennew.j2etcdV3.proto.etcdserverpb;

public final class Etcdserver {
  private Etcdserver() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:etcdserverpb.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 ID = 1;</code>
     */
    boolean hasID();
    /**
     * <code>optional uint64 ID = 1;</code>
     */
    long getID();

    /**
     * <code>optional string Method = 2;</code>
     */
    boolean hasMethod();
    /**
     * <code>optional string Method = 2;</code>
     */
    java.lang.String getMethod();
    /**
     * <code>optional string Method = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    /**
     * <code>optional string Path = 3;</code>
     */
    boolean hasPath();
    /**
     * <code>optional string Path = 3;</code>
     */
    java.lang.String getPath();
    /**
     * <code>optional string Path = 3;</code>
     */
    com.google.protobuf.ByteString
        getPathBytes();

    /**
     * <code>optional string Val = 4;</code>
     */
    boolean hasVal();
    /**
     * <code>optional string Val = 4;</code>
     */
    java.lang.String getVal();
    /**
     * <code>optional string Val = 4;</code>
     */
    com.google.protobuf.ByteString
        getValBytes();

    /**
     * <code>optional bool Dir = 5;</code>
     */
    boolean hasDir();
    /**
     * <code>optional bool Dir = 5;</code>
     */
    boolean getDir();

    /**
     * <code>optional string PrevValue = 6;</code>
     */
    boolean hasPrevValue();
    /**
     * <code>optional string PrevValue = 6;</code>
     */
    java.lang.String getPrevValue();
    /**
     * <code>optional string PrevValue = 6;</code>
     */
    com.google.protobuf.ByteString
        getPrevValueBytes();

    /**
     * <code>optional uint64 PrevIndex = 7;</code>
     */
    boolean hasPrevIndex();
    /**
     * <code>optional uint64 PrevIndex = 7;</code>
     */
    long getPrevIndex();

    /**
     * <code>optional bool PrevExist = 8;</code>
     */
    boolean hasPrevExist();
    /**
     * <code>optional bool PrevExist = 8;</code>
     */
    boolean getPrevExist();

    /**
     * <code>optional int64 Expiration = 9;</code>
     */
    boolean hasExpiration();
    /**
     * <code>optional int64 Expiration = 9;</code>
     */
    long getExpiration();

    /**
     * <code>optional bool Wait = 10;</code>
     */
    boolean hasWait();
    /**
     * <code>optional bool Wait = 10;</code>
     */
    boolean getWait();

    /**
     * <code>optional uint64 Since = 11;</code>
     */
    boolean hasSince();
    /**
     * <code>optional uint64 Since = 11;</code>
     */
    long getSince();

    /**
     * <code>optional bool Recursive = 12;</code>
     */
    boolean hasRecursive();
    /**
     * <code>optional bool Recursive = 12;</code>
     */
    boolean getRecursive();

    /**
     * <code>optional bool Sorted = 13;</code>
     */
    boolean hasSorted();
    /**
     * <code>optional bool Sorted = 13;</code>
     */
    boolean getSorted();

    /**
     * <code>optional bool Quorum = 14;</code>
     */
    boolean hasQuorum();
    /**
     * <code>optional bool Quorum = 14;</code>
     */
    boolean getQuorum();

    /**
     * <code>optional int64 Time = 15;</code>
     */
    boolean hasTime();
    /**
     * <code>optional int64 Time = 15;</code>
     */
    long getTime();

    /**
     * <code>optional bool Stream = 16;</code>
     */
    boolean hasStream();
    /**
     * <code>optional bool Stream = 16;</code>
     */
    boolean getStream();

    /**
     * <code>optional bool Refresh = 17;</code>
     */
    boolean hasRefresh();
    /**
     * <code>optional bool Refresh = 17;</code>
     */
    boolean getRefresh();
  }
  /**
   * Protobuf type {@code etcdserverpb.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:etcdserverpb.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      iD_ = 0L;
      method_ = "";
      path_ = "";
      val_ = "";
      dir_ = false;
      prevValue_ = "";
      prevIndex_ = 0L;
      prevExist_ = false;
      expiration_ = 0L;
      wait_ = false;
      since_ = 0L;
      recursive_ = false;
      sorted_ = false;
      quorum_ = false;
      time_ = 0L;
      stream_ = false;
      refresh_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              iD_ = input.readUInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              method_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              path_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              val_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              dir_ = input.readBool();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              prevValue_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              prevIndex_ = input.readUInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              prevExist_ = input.readBool();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              expiration_ = input.readInt64();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              wait_ = input.readBool();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              since_ = input.readUInt64();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              recursive_ = input.readBool();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              sorted_ = input.readBool();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              quorum_ = input.readBool();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              time_ = input.readInt64();
              break;
            }
            case 128: {
              bitField0_ |= 0x00008000;
              stream_ = input.readBool();
              break;
            }
            case 136: {
              bitField0_ |= 0x00010000;
              refresh_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.internal_static_etcdserverpb_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.internal_static_etcdserverpb_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request.class, com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long iD_;
    /**
     * <code>optional uint64 ID = 1;</code>
     */
    public boolean hasID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 ID = 1;</code>
     */
    public long getID() {
      return iD_;
    }

    public static final int METHOD_FIELD_NUMBER = 2;
    private volatile java.lang.Object method_;
    /**
     * <code>optional string Method = 2;</code>
     */
    public boolean hasMethod() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string Method = 2;</code>
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          method_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Method = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PATH_FIELD_NUMBER = 3;
    private volatile java.lang.Object path_;
    /**
     * <code>optional string Path = 3;</code>
     */
    public boolean hasPath() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string Path = 3;</code>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          path_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Path = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VAL_FIELD_NUMBER = 4;
    private volatile java.lang.Object val_;
    /**
     * <code>optional string Val = 4;</code>
     */
    public boolean hasVal() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string Val = 4;</code>
     */
    public java.lang.String getVal() {
      java.lang.Object ref = val_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          val_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Val = 4;</code>
     */
    public com.google.protobuf.ByteString
        getValBytes() {
      java.lang.Object ref = val_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        val_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIR_FIELD_NUMBER = 5;
    private boolean dir_;
    /**
     * <code>optional bool Dir = 5;</code>
     */
    public boolean hasDir() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool Dir = 5;</code>
     */
    public boolean getDir() {
      return dir_;
    }

    public static final int PREVVALUE_FIELD_NUMBER = 6;
    private volatile java.lang.Object prevValue_;
    /**
     * <code>optional string PrevValue = 6;</code>
     */
    public boolean hasPrevValue() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string PrevValue = 6;</code>
     */
    public java.lang.String getPrevValue() {
      java.lang.Object ref = prevValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          prevValue_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string PrevValue = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPrevValueBytes() {
      java.lang.Object ref = prevValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prevValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PREVINDEX_FIELD_NUMBER = 7;
    private long prevIndex_;
    /**
     * <code>optional uint64 PrevIndex = 7;</code>
     */
    public boolean hasPrevIndex() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint64 PrevIndex = 7;</code>
     */
    public long getPrevIndex() {
      return prevIndex_;
    }

    public static final int PREVEXIST_FIELD_NUMBER = 8;
    private boolean prevExist_;
    /**
     * <code>optional bool PrevExist = 8;</code>
     */
    public boolean hasPrevExist() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional bool PrevExist = 8;</code>
     */
    public boolean getPrevExist() {
      return prevExist_;
    }

    public static final int EXPIRATION_FIELD_NUMBER = 9;
    private long expiration_;
    /**
     * <code>optional int64 Expiration = 9;</code>
     */
    public boolean hasExpiration() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int64 Expiration = 9;</code>
     */
    public long getExpiration() {
      return expiration_;
    }

    public static final int WAIT_FIELD_NUMBER = 10;
    private boolean wait_;
    /**
     * <code>optional bool Wait = 10;</code>
     */
    public boolean hasWait() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional bool Wait = 10;</code>
     */
    public boolean getWait() {
      return wait_;
    }

    public static final int SINCE_FIELD_NUMBER = 11;
    private long since_;
    /**
     * <code>optional uint64 Since = 11;</code>
     */
    public boolean hasSince() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional uint64 Since = 11;</code>
     */
    public long getSince() {
      return since_;
    }

    public static final int RECURSIVE_FIELD_NUMBER = 12;
    private boolean recursive_;
    /**
     * <code>optional bool Recursive = 12;</code>
     */
    public boolean hasRecursive() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional bool Recursive = 12;</code>
     */
    public boolean getRecursive() {
      return recursive_;
    }

    public static final int SORTED_FIELD_NUMBER = 13;
    private boolean sorted_;
    /**
     * <code>optional bool Sorted = 13;</code>
     */
    public boolean hasSorted() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional bool Sorted = 13;</code>
     */
    public boolean getSorted() {
      return sorted_;
    }

    public static final int QUORUM_FIELD_NUMBER = 14;
    private boolean quorum_;
    /**
     * <code>optional bool Quorum = 14;</code>
     */
    public boolean hasQuorum() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional bool Quorum = 14;</code>
     */
    public boolean getQuorum() {
      return quorum_;
    }

    public static final int TIME_FIELD_NUMBER = 15;
    private long time_;
    /**
     * <code>optional int64 Time = 15;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional int64 Time = 15;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int STREAM_FIELD_NUMBER = 16;
    private boolean stream_;
    /**
     * <code>optional bool Stream = 16;</code>
     */
    public boolean hasStream() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional bool Stream = 16;</code>
     */
    public boolean getStream() {
      return stream_;
    }

    public static final int REFRESH_FIELD_NUMBER = 17;
    private boolean refresh_;
    /**
     * <code>optional bool Refresh = 17;</code>
     */
    public boolean hasRefresh() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>optional bool Refresh = 17;</code>
     */
    public boolean getRefresh() {
      return refresh_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, iD_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, method_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, path_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, val_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, dir_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, prevValue_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt64(7, prevIndex_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBool(8, prevExist_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt64(9, expiration_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBool(10, wait_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeUInt64(11, since_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBool(12, recursive_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBool(13, sorted_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBool(14, quorum_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt64(15, time_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeBool(16, stream_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeBool(17, refresh_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, iD_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, method_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, path_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, val_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, dir_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, prevValue_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, prevIndex_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, prevExist_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, expiration_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, wait_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(11, since_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(12, recursive_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(13, sorted_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(14, quorum_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(15, time_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(16, stream_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(17, refresh_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request)) {
        return super.equals(obj);
      }
      com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request other = (com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request) obj;

      boolean result = true;
      result = result && (hasID() == other.hasID());
      if (hasID()) {
        result = result && (getID()
            == other.getID());
      }
      result = result && (hasMethod() == other.hasMethod());
      if (hasMethod()) {
        result = result && getMethod()
            .equals(other.getMethod());
      }
      result = result && (hasPath() == other.hasPath());
      if (hasPath()) {
        result = result && getPath()
            .equals(other.getPath());
      }
      result = result && (hasVal() == other.hasVal());
      if (hasVal()) {
        result = result && getVal()
            .equals(other.getVal());
      }
      result = result && (hasDir() == other.hasDir());
      if (hasDir()) {
        result = result && (getDir()
            == other.getDir());
      }
      result = result && (hasPrevValue() == other.hasPrevValue());
      if (hasPrevValue()) {
        result = result && getPrevValue()
            .equals(other.getPrevValue());
      }
      result = result && (hasPrevIndex() == other.hasPrevIndex());
      if (hasPrevIndex()) {
        result = result && (getPrevIndex()
            == other.getPrevIndex());
      }
      result = result && (hasPrevExist() == other.hasPrevExist());
      if (hasPrevExist()) {
        result = result && (getPrevExist()
            == other.getPrevExist());
      }
      result = result && (hasExpiration() == other.hasExpiration());
      if (hasExpiration()) {
        result = result && (getExpiration()
            == other.getExpiration());
      }
      result = result && (hasWait() == other.hasWait());
      if (hasWait()) {
        result = result && (getWait()
            == other.getWait());
      }
      result = result && (hasSince() == other.hasSince());
      if (hasSince()) {
        result = result && (getSince()
            == other.getSince());
      }
      result = result && (hasRecursive() == other.hasRecursive());
      if (hasRecursive()) {
        result = result && (getRecursive()
            == other.getRecursive());
      }
      result = result && (hasSorted() == other.hasSorted());
      if (hasSorted()) {
        result = result && (getSorted()
            == other.getSorted());
      }
      result = result && (hasQuorum() == other.hasQuorum());
      if (hasQuorum()) {
        result = result && (getQuorum()
            == other.getQuorum());
      }
      result = result && (hasTime() == other.hasTime());
      if (hasTime()) {
        result = result && (getTime()
            == other.getTime());
      }
      result = result && (hasStream() == other.hasStream());
      if (hasStream()) {
        result = result && (getStream()
            == other.getStream());
      }
      result = result && (hasRefresh() == other.hasRefresh());
      if (hasRefresh()) {
        result = result && (getRefresh()
            == other.getRefresh());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasID()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getID());
      }
      if (hasMethod()) {
        hash = (37 * hash) + METHOD_FIELD_NUMBER;
        hash = (53 * hash) + getMethod().hashCode();
      }
      if (hasPath()) {
        hash = (37 * hash) + PATH_FIELD_NUMBER;
        hash = (53 * hash) + getPath().hashCode();
      }
      if (hasVal()) {
        hash = (37 * hash) + VAL_FIELD_NUMBER;
        hash = (53 * hash) + getVal().hashCode();
      }
      if (hasDir()) {
        hash = (37 * hash) + DIR_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getDir());
      }
      if (hasPrevValue()) {
        hash = (37 * hash) + PREVVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getPrevValue().hashCode();
      }
      if (hasPrevIndex()) {
        hash = (37 * hash) + PREVINDEX_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPrevIndex());
      }
      if (hasPrevExist()) {
        hash = (37 * hash) + PREVEXIST_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getPrevExist());
      }
      if (hasExpiration()) {
        hash = (37 * hash) + EXPIRATION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getExpiration());
      }
      if (hasWait()) {
        hash = (37 * hash) + WAIT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getWait());
      }
      if (hasSince()) {
        hash = (37 * hash) + SINCE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSince());
      }
      if (hasRecursive()) {
        hash = (37 * hash) + RECURSIVE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getRecursive());
      }
      if (hasSorted()) {
        hash = (37 * hash) + SORTED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getSorted());
      }
      if (hasQuorum()) {
        hash = (37 * hash) + QUORUM_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getQuorum());
      }
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTime());
      }
      if (hasStream()) {
        hash = (37 * hash) + STREAM_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getStream());
      }
      if (hasRefresh()) {
        hash = (37 * hash) + REFRESH_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getRefresh());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code etcdserverpb.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:etcdserverpb.Request)
        com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.internal_static_etcdserverpb_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.internal_static_etcdserverpb_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request.class, com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request.Builder.class);
      }

      // Construct using com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        iD_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        method_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        path_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        val_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        dir_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        prevValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        prevIndex_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        prevExist_ = false;
        bitField0_ = (bitField0_ & ~0x00000080);
        expiration_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        wait_ = false;
        bitField0_ = (bitField0_ & ~0x00000200);
        since_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        recursive_ = false;
        bitField0_ = (bitField0_ & ~0x00000800);
        sorted_ = false;
        bitField0_ = (bitField0_ & ~0x00001000);
        quorum_ = false;
        bitField0_ = (bitField0_ & ~0x00002000);
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00004000);
        stream_ = false;
        bitField0_ = (bitField0_ & ~0x00008000);
        refresh_ = false;
        bitField0_ = (bitField0_ & ~0x00010000);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.internal_static_etcdserverpb_Request_descriptor;
      }

      public com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request getDefaultInstanceForType() {
        return com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request.getDefaultInstance();
      }

      public com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request build() {
        com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request buildPartial() {
        com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request result = new com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.iD_ = iD_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.method_ = method_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.path_ = path_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.val_ = val_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.dir_ = dir_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.prevValue_ = prevValue_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.prevIndex_ = prevIndex_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.prevExist_ = prevExist_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.expiration_ = expiration_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.wait_ = wait_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.since_ = since_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.recursive_ = recursive_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.sorted_ = sorted_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.quorum_ = quorum_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.stream_ = stream_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.refresh_ = refresh_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request) {
          return mergeFrom((com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request other) {
        if (other == com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request.getDefaultInstance()) return this;
        if (other.hasID()) {
          setID(other.getID());
        }
        if (other.hasMethod()) {
          bitField0_ |= 0x00000002;
          method_ = other.method_;
          onChanged();
        }
        if (other.hasPath()) {
          bitField0_ |= 0x00000004;
          path_ = other.path_;
          onChanged();
        }
        if (other.hasVal()) {
          bitField0_ |= 0x00000008;
          val_ = other.val_;
          onChanged();
        }
        if (other.hasDir()) {
          setDir(other.getDir());
        }
        if (other.hasPrevValue()) {
          bitField0_ |= 0x00000020;
          prevValue_ = other.prevValue_;
          onChanged();
        }
        if (other.hasPrevIndex()) {
          setPrevIndex(other.getPrevIndex());
        }
        if (other.hasPrevExist()) {
          setPrevExist(other.getPrevExist());
        }
        if (other.hasExpiration()) {
          setExpiration(other.getExpiration());
        }
        if (other.hasWait()) {
          setWait(other.getWait());
        }
        if (other.hasSince()) {
          setSince(other.getSince());
        }
        if (other.hasRecursive()) {
          setRecursive(other.getRecursive());
        }
        if (other.hasSorted()) {
          setSorted(other.getSorted());
        }
        if (other.hasQuorum()) {
          setQuorum(other.getQuorum());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasStream()) {
          setStream(other.getStream());
        }
        if (other.hasRefresh()) {
          setRefresh(other.getRefresh());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long iD_ ;
      /**
       * <code>optional uint64 ID = 1;</code>
       */
      public boolean hasID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 ID = 1;</code>
       */
      public long getID() {
        return iD_;
      }
      /**
       * <code>optional uint64 ID = 1;</code>
       */
      public Builder setID(long value) {
        bitField0_ |= 0x00000001;
        iD_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 ID = 1;</code>
       */
      public Builder clearID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        iD_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object method_ = "";
      /**
       * <code>optional string Method = 2;</code>
       */
      public boolean hasMethod() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string Method = 2;</code>
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            method_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Method = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Method = 2;</code>
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Method = 2;</code>
       */
      public Builder clearMethod() {
        bitField0_ = (bitField0_ & ~0x00000002);
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Method = 2;</code>
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        method_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object path_ = "";
      /**
       * <code>optional string Path = 3;</code>
       */
      public boolean hasPath() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string Path = 3;</code>
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            path_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Path = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Path = 3;</code>
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Path = 3;</code>
       */
      public Builder clearPath() {
        bitField0_ = (bitField0_ & ~0x00000004);
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Path = 3;</code>
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        path_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object val_ = "";
      /**
       * <code>optional string Val = 4;</code>
       */
      public boolean hasVal() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string Val = 4;</code>
       */
      public java.lang.String getVal() {
        java.lang.Object ref = val_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            val_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Val = 4;</code>
       */
      public com.google.protobuf.ByteString
          getValBytes() {
        java.lang.Object ref = val_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          val_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Val = 4;</code>
       */
      public Builder setVal(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        val_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Val = 4;</code>
       */
      public Builder clearVal() {
        bitField0_ = (bitField0_ & ~0x00000008);
        val_ = getDefaultInstance().getVal();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Val = 4;</code>
       */
      public Builder setValBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        val_ = value;
        onChanged();
        return this;
      }

      private boolean dir_ ;
      /**
       * <code>optional bool Dir = 5;</code>
       */
      public boolean hasDir() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool Dir = 5;</code>
       */
      public boolean getDir() {
        return dir_;
      }
      /**
       * <code>optional bool Dir = 5;</code>
       */
      public Builder setDir(boolean value) {
        bitField0_ |= 0x00000010;
        dir_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool Dir = 5;</code>
       */
      public Builder clearDir() {
        bitField0_ = (bitField0_ & ~0x00000010);
        dir_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object prevValue_ = "";
      /**
       * <code>optional string PrevValue = 6;</code>
       */
      public boolean hasPrevValue() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string PrevValue = 6;</code>
       */
      public java.lang.String getPrevValue() {
        java.lang.Object ref = prevValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            prevValue_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string PrevValue = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPrevValueBytes() {
        java.lang.Object ref = prevValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          prevValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string PrevValue = 6;</code>
       */
      public Builder setPrevValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        prevValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string PrevValue = 6;</code>
       */
      public Builder clearPrevValue() {
        bitField0_ = (bitField0_ & ~0x00000020);
        prevValue_ = getDefaultInstance().getPrevValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string PrevValue = 6;</code>
       */
      public Builder setPrevValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        prevValue_ = value;
        onChanged();
        return this;
      }

      private long prevIndex_ ;
      /**
       * <code>optional uint64 PrevIndex = 7;</code>
       */
      public boolean hasPrevIndex() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional uint64 PrevIndex = 7;</code>
       */
      public long getPrevIndex() {
        return prevIndex_;
      }
      /**
       * <code>optional uint64 PrevIndex = 7;</code>
       */
      public Builder setPrevIndex(long value) {
        bitField0_ |= 0x00000040;
        prevIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 PrevIndex = 7;</code>
       */
      public Builder clearPrevIndex() {
        bitField0_ = (bitField0_ & ~0x00000040);
        prevIndex_ = 0L;
        onChanged();
        return this;
      }

      private boolean prevExist_ ;
      /**
       * <code>optional bool PrevExist = 8;</code>
       */
      public boolean hasPrevExist() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bool PrevExist = 8;</code>
       */
      public boolean getPrevExist() {
        return prevExist_;
      }
      /**
       * <code>optional bool PrevExist = 8;</code>
       */
      public Builder setPrevExist(boolean value) {
        bitField0_ |= 0x00000080;
        prevExist_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool PrevExist = 8;</code>
       */
      public Builder clearPrevExist() {
        bitField0_ = (bitField0_ & ~0x00000080);
        prevExist_ = false;
        onChanged();
        return this;
      }

      private long expiration_ ;
      /**
       * <code>optional int64 Expiration = 9;</code>
       */
      public boolean hasExpiration() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int64 Expiration = 9;</code>
       */
      public long getExpiration() {
        return expiration_;
      }
      /**
       * <code>optional int64 Expiration = 9;</code>
       */
      public Builder setExpiration(long value) {
        bitField0_ |= 0x00000100;
        expiration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Expiration = 9;</code>
       */
      public Builder clearExpiration() {
        bitField0_ = (bitField0_ & ~0x00000100);
        expiration_ = 0L;
        onChanged();
        return this;
      }

      private boolean wait_ ;
      /**
       * <code>optional bool Wait = 10;</code>
       */
      public boolean hasWait() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional bool Wait = 10;</code>
       */
      public boolean getWait() {
        return wait_;
      }
      /**
       * <code>optional bool Wait = 10;</code>
       */
      public Builder setWait(boolean value) {
        bitField0_ |= 0x00000200;
        wait_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool Wait = 10;</code>
       */
      public Builder clearWait() {
        bitField0_ = (bitField0_ & ~0x00000200);
        wait_ = false;
        onChanged();
        return this;
      }

      private long since_ ;
      /**
       * <code>optional uint64 Since = 11;</code>
       */
      public boolean hasSince() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional uint64 Since = 11;</code>
       */
      public long getSince() {
        return since_;
      }
      /**
       * <code>optional uint64 Since = 11;</code>
       */
      public Builder setSince(long value) {
        bitField0_ |= 0x00000400;
        since_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 Since = 11;</code>
       */
      public Builder clearSince() {
        bitField0_ = (bitField0_ & ~0x00000400);
        since_ = 0L;
        onChanged();
        return this;
      }

      private boolean recursive_ ;
      /**
       * <code>optional bool Recursive = 12;</code>
       */
      public boolean hasRecursive() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional bool Recursive = 12;</code>
       */
      public boolean getRecursive() {
        return recursive_;
      }
      /**
       * <code>optional bool Recursive = 12;</code>
       */
      public Builder setRecursive(boolean value) {
        bitField0_ |= 0x00000800;
        recursive_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool Recursive = 12;</code>
       */
      public Builder clearRecursive() {
        bitField0_ = (bitField0_ & ~0x00000800);
        recursive_ = false;
        onChanged();
        return this;
      }

      private boolean sorted_ ;
      /**
       * <code>optional bool Sorted = 13;</code>
       */
      public boolean hasSorted() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional bool Sorted = 13;</code>
       */
      public boolean getSorted() {
        return sorted_;
      }
      /**
       * <code>optional bool Sorted = 13;</code>
       */
      public Builder setSorted(boolean value) {
        bitField0_ |= 0x00001000;
        sorted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool Sorted = 13;</code>
       */
      public Builder clearSorted() {
        bitField0_ = (bitField0_ & ~0x00001000);
        sorted_ = false;
        onChanged();
        return this;
      }

      private boolean quorum_ ;
      /**
       * <code>optional bool Quorum = 14;</code>
       */
      public boolean hasQuorum() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional bool Quorum = 14;</code>
       */
      public boolean getQuorum() {
        return quorum_;
      }
      /**
       * <code>optional bool Quorum = 14;</code>
       */
      public Builder setQuorum(boolean value) {
        bitField0_ |= 0x00002000;
        quorum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool Quorum = 14;</code>
       */
      public Builder clearQuorum() {
        bitField0_ = (bitField0_ & ~0x00002000);
        quorum_ = false;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>optional int64 Time = 15;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional int64 Time = 15;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>optional int64 Time = 15;</code>
       */
      public Builder setTime(long value) {
        bitField0_ |= 0x00004000;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Time = 15;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00004000);
        time_ = 0L;
        onChanged();
        return this;
      }

      private boolean stream_ ;
      /**
       * <code>optional bool Stream = 16;</code>
       */
      public boolean hasStream() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional bool Stream = 16;</code>
       */
      public boolean getStream() {
        return stream_;
      }
      /**
       * <code>optional bool Stream = 16;</code>
       */
      public Builder setStream(boolean value) {
        bitField0_ |= 0x00008000;
        stream_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool Stream = 16;</code>
       */
      public Builder clearStream() {
        bitField0_ = (bitField0_ & ~0x00008000);
        stream_ = false;
        onChanged();
        return this;
      }

      private boolean refresh_ ;
      /**
       * <code>optional bool Refresh = 17;</code>
       */
      public boolean hasRefresh() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>optional bool Refresh = 17;</code>
       */
      public boolean getRefresh() {
        return refresh_;
      }
      /**
       * <code>optional bool Refresh = 17;</code>
       */
      public Builder setRefresh(boolean value) {
        bitField0_ |= 0x00010000;
        refresh_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool Refresh = 17;</code>
       */
      public Builder clearRefresh() {
        bitField0_ = (bitField0_ & ~0x00010000);
        refresh_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:etcdserverpb.Request)
    }

    // @@protoc_insertion_point(class_scope:etcdserverpb.Request)
    private static final com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request();
    }

    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:etcdserverpb.Metadata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 NodeID = 1;</code>
     */
    boolean hasNodeID();
    /**
     * <code>optional uint64 NodeID = 1;</code>
     */
    long getNodeID();

    /**
     * <code>optional uint64 ClusterID = 2;</code>
     */
    boolean hasClusterID();
    /**
     * <code>optional uint64 ClusterID = 2;</code>
     */
    long getClusterID();
  }
  /**
   * Protobuf type {@code etcdserverpb.Metadata}
   */
  public  static final class Metadata extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:etcdserverpb.Metadata)
      MetadataOrBuilder {
    // Use Metadata.newBuilder() to construct.
    private Metadata(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Metadata() {
      nodeID_ = 0L;
      clusterID_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Metadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              nodeID_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              clusterID_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.internal_static_etcdserverpb_Metadata_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.internal_static_etcdserverpb_Metadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata.class, com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata.Builder.class);
    }

    private int bitField0_;
    public static final int NODEID_FIELD_NUMBER = 1;
    private long nodeID_;
    /**
     * <code>optional uint64 NodeID = 1;</code>
     */
    public boolean hasNodeID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 NodeID = 1;</code>
     */
    public long getNodeID() {
      return nodeID_;
    }

    public static final int CLUSTERID_FIELD_NUMBER = 2;
    private long clusterID_;
    /**
     * <code>optional uint64 ClusterID = 2;</code>
     */
    public boolean hasClusterID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 ClusterID = 2;</code>
     */
    public long getClusterID() {
      return clusterID_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, nodeID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, clusterID_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, nodeID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, clusterID_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata)) {
        return super.equals(obj);
      }
      com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata other = (com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata) obj;

      boolean result = true;
      result = result && (hasNodeID() == other.hasNodeID());
      if (hasNodeID()) {
        result = result && (getNodeID()
            == other.getNodeID());
      }
      result = result && (hasClusterID() == other.hasClusterID());
      if (hasClusterID()) {
        result = result && (getClusterID()
            == other.getClusterID());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasNodeID()) {
        hash = (37 * hash) + NODEID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getNodeID());
      }
      if (hasClusterID()) {
        hash = (37 * hash) + CLUSTERID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getClusterID());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code etcdserverpb.Metadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:etcdserverpb.Metadata)
        com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.MetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.internal_static_etcdserverpb_Metadata_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.internal_static_etcdserverpb_Metadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata.class, com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata.Builder.class);
      }

      // Construct using com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        nodeID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        clusterID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.internal_static_etcdserverpb_Metadata_descriptor;
      }

      public com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata getDefaultInstanceForType() {
        return com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata.getDefaultInstance();
      }

      public com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata build() {
        com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata buildPartial() {
        com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata result = new com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nodeID_ = nodeID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clusterID_ = clusterID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata) {
          return mergeFrom((com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata other) {
        if (other == com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata.getDefaultInstance()) return this;
        if (other.hasNodeID()) {
          setNodeID(other.getNodeID());
        }
        if (other.hasClusterID()) {
          setClusterID(other.getClusterID());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long nodeID_ ;
      /**
       * <code>optional uint64 NodeID = 1;</code>
       */
      public boolean hasNodeID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 NodeID = 1;</code>
       */
      public long getNodeID() {
        return nodeID_;
      }
      /**
       * <code>optional uint64 NodeID = 1;</code>
       */
      public Builder setNodeID(long value) {
        bitField0_ |= 0x00000001;
        nodeID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 NodeID = 1;</code>
       */
      public Builder clearNodeID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeID_ = 0L;
        onChanged();
        return this;
      }

      private long clusterID_ ;
      /**
       * <code>optional uint64 ClusterID = 2;</code>
       */
      public boolean hasClusterID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 ClusterID = 2;</code>
       */
      public long getClusterID() {
        return clusterID_;
      }
      /**
       * <code>optional uint64 ClusterID = 2;</code>
       */
      public Builder setClusterID(long value) {
        bitField0_ |= 0x00000002;
        clusterID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 ClusterID = 2;</code>
       */
      public Builder clearClusterID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clusterID_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:etcdserverpb.Metadata)
    }

    // @@protoc_insertion_point(class_scope:etcdserverpb.Metadata)
    private static final com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata();
    }

    public static com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Metadata>
        PARSER = new com.google.protobuf.AbstractParser<Metadata>() {
      public Metadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Metadata(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Metadata> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Metadata> getParserForType() {
      return PARSER;
    }

    public com.ennew.j2etcdV3.proto.etcdserverpb.Etcdserver.Metadata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_etcdserverpb_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_etcdserverpb_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_etcdserverpb_Metadata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_etcdserverpb_Metadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020etcdserver.proto\022\014etcdserverpb\032\024gogopr" +
      "oto/gogo.proto\"\377\002\n\007Request\022\020\n\002ID\030\001 \001(\004B\004" +
      "\310\336\037\000\022\024\n\006Method\030\002 \001(\tB\004\310\336\037\000\022\022\n\004Path\030\003 \001(\t" +
      "B\004\310\336\037\000\022\021\n\003Val\030\004 \001(\tB\004\310\336\037\000\022\021\n\003Dir\030\005 \001(\010B\004" +
      "\310\336\037\000\022\027\n\tPrevValue\030\006 \001(\tB\004\310\336\037\000\022\027\n\tPrevInd" +
      "ex\030\007 \001(\004B\004\310\336\037\000\022\027\n\tPrevExist\030\010 \001(\010B\004\310\336\037\001\022" +
      "\030\n\nExpiration\030\t \001(\003B\004\310\336\037\000\022\022\n\004Wait\030\n \001(\010B" +
      "\004\310\336\037\000\022\023\n\005Since\030\013 \001(\004B\004\310\336\037\000\022\027\n\tRecursive\030" +
      "\014 \001(\010B\004\310\336\037\000\022\024\n\006Sorted\030\r \001(\010B\004\310\336\037\000\022\024\n\006Quo" +
      "rum\030\016 \001(\010B\004\310\336\037\000\022\022\n\004Time\030\017 \001(\003B\004\310\336\037\000\022\024\n\006S",
      "tream\030\020 \001(\010B\004\310\336\037\000\022\025\n\007Refresh\030\021 \001(\010B\004\310\336\037\001" +
      "\"9\n\010Metadata\022\024\n\006NodeID\030\001 \001(\004B\004\310\336\037\000\022\027\n\tCl" +
      "usterID\030\002 \001(\004B\004\310\336\037\000B7\n%com.ennew.j2etcdV" +
      "3.proto.etcdserverpb\310\342\036\001\340\342\036\001\320\342\036\001\310\341\036\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        }, assigner);
    internal_static_etcdserverpb_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_etcdserverpb_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_etcdserverpb_Request_descriptor,
        new java.lang.String[] { "ID", "Method", "Path", "Val", "Dir", "PrevValue", "PrevIndex", "PrevExist", "Expiration", "Wait", "Since", "Recursive", "Sorted", "Quorum", "Time", "Stream", "Refresh", });
    internal_static_etcdserverpb_Metadata_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_etcdserverpb_Metadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_etcdserverpb_Metadata_descriptor,
        new java.lang.String[] { "NodeID", "ClusterID", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.goprotoGettersAll);
    registry.add(com.google.protobuf.GoGoProtos.marshalerAll);
    registry.add(com.google.protobuf.GoGoProtos.nullable);
    registry.add(com.google.protobuf.GoGoProtos.sizerAll);
    registry.add(com.google.protobuf.GoGoProtos.unmarshalerAll);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
